### ISSUE TITLE
how can i get the numbers for the regionFlag ?

### ISSUE THREAD

**Issue by Doritao** [dnsge/puzzle-bot#1]
how can i get the numbers for the regionFlag ?
i dont know how to do it

**Comment by dnsge** [comment]
There really isn't an easy way to find the numbers. To get the exact row and column number, you would have to count out the pieces and locate the region you want to solve manually.

If you have already completed the puzzle's edges, you can find the row and column by counting along the edge.

If you aren't trying to be super precise, you can just try different values and run the command multiple times until it does the whole region that you want.
