### ISSUE TITLE
Joined Puzzle server version x

### ISSUE THREAD

**Issue by owuiviuwo** [dnsge/puzzle-bot#2]
Hi, I met the problem about the server version. I made several try but all failed. I would be really appreciated to know how to fix it. Thanks a lot!

Here is the command info.

<img width="813" alt="image" src="https://user-images.githubusercontent.com/121178977/214933842-06184924-596c-4757-9fa4-f101fa3472c8.png">

And below is the web info 

<img width="416" alt="image" src="https://user-images.githubusercontent.com/121178977/214933991-f8705ced-419b-4e13-8b25-2400b4516853.png">

**Comment by dnsge** [comment]
Hey, thanks for the issue. It seems like the way that users connect to the server has changed and a new challenge has been introduced. I'll see what can be done to still connect.

**Comment by dnsge** [comment]
I looked into the website's changes (clearly made to prevent automated scripts) and decided that it's too much work for me to fix the library. I added code to solve the new dynamic challenges but found that simple things like combining pieces was now broken, too. 

Here is the message I've added to the README, for completeness:

> This library is now broken. I do not plan to update it. I added code to compute a dynamic challenge introduced to prove that the user is using a browser, but it seems like message construction was changed. I don't feel like reverse engineering the puzzle website's code again, but people are welcome to try on their own. Sorry!
